{% set mpi = os.environ.get('MPI') or 'mpich' %}
{% set req = {'mpich':'>=3.2', 'openmpi':'>=2.0.1'} %}

package:
  name: h5py-parallel
  version: "2.7.0"

source:
  fn: 2.7.0rc2.tar.gz
  url: https://github.com/h5py/h5py/archive/2.7.0rc2.tar.gz
  md5: 09dab86c5758f631cfce85dc9cd1a9f0

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  build:
    - python
    - numpy
    - cython
    #- {{mpi}}  {{req[mpi]}}
    - mpi4py
    - six
    - pkgconfig
    - hdf5-parallel 1.8.14

  run:
    - python
    - numpy
    #- {{mpi}}  {{req[mpi]}}
    - mpi4py
    - hdf5-parallel 1.8.14
    - six

test:
  imports:
    - h5py
