{% set mpi = os.environ.get('MPI') or 'mpich' %}
{% set req = {'mpich':'>=3.2', 'openmpi':'>=2.0.1'} %}

package:
  name: hdf5-parallel
  version: 1.8.17

source:
  fn: hdf5-1.8.17.tar.bz2
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.17/src/hdf5-1.8.17.tar.bz2
  md5: 34bd1afa5209259201a41964100d6203

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  build:
    - python
    - zlib 1.2.*
    - mpich
    - gcc 4.8.*
    - libgcc 4.8.*

  run:
    - zlib

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD-style (http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING)
