package:
  name: fenics
  version: {{FENICS_VERSION}}
  
build:
  number: {{CONDA_BUILD_NUMBER}}
  features:
    - vtk
  
requirements:
  run:
    - vtk ==5.10.1
    - dolfin =={{FENICS_VERSION}}

about:
  home: http://www.fenicsproject.org
  summary: 'FEniCS is a collection of free software for automated, efficient solution of differential equations'

