package:
  name: instant
  version: {{FENICS_VERSION}}

source:
  git_url: https://bitbucket.org/fenics-project/instant
  git_tag: master 
  #git_tag: instant-{{FENICS_GIT_TAG}}

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  build:            
    - python
    - numpy

  run:
    - python
    - numpy
    #- cmake
    - swig

test:
  imports:
    - instant

  commands:
    - instant-clean
    - instant-showcache

  requires:
    - pytest

about:
  home: http://www.fenicsproject.org
  license: BSD License or The GNU Lesser General Public License, version 3.0
  summary: 'Instant Inlining of C/C++ in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
