package:
  name: dolfin
  version: {{FENICS_VERSION}}

source:
  git_url: https://bitbucket.org/fenics-project/dolfin
  git_tag: master 
  #git_tag: dolfin-{{FENICS_GIT_TAG}}

build:
  number: {{CONDA_BUILD_NUMBER}}
  features:
    - vtk

requirements:
  build:
    - python
    #- cmake
    - sphinx
    - libxml2
    - swig 
    - numpy
    - mpi4py
    - vtk ==5.10.1
    - ffc =={{FENICS_VERSION}}
    - ply ==3.8
    - boost
    - eigen3
    - petsc <=3.7.3
    - petsc4py <=3.7.0
    - slepc <=3.7.2
    - hdf5-parallel

  run:
    - python
    - libxml2
    - swig
    - numpy
    - mpi4py
    - vtk ==5.10.1
    - ffc =={{FENICS_VERSION}}
    - ufl =={{FENICS_VERSION}}
    - ply ==3.8
    - boost
    - eigen3
    - petsc <=3.7.3
    - petsc4py <=3.7.0
    - slepc <=3.7.2
    - hdf5-parallel

test:
  imports:
    - dolfin

about:
  home: http://www.fenicsproject.org
  license: The GNU Lesser General Public License, version 3.0
  summary: 'C++/Python library for solving differential equations'
