{% set version = '3.8.1' %}
{% set sha256 = 'd7b72c3337ddc56031d39d0b52d7f28b61ecc41b755ae853d23f34912b4f3c92' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}

package:
  name: petsc4py
  version: {{version}}

source:
  fn: petsc4py-{{version}}.tar.gz
  url: https://bitbucket.org/petsc/petsc4py/downloads/petsc4py-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  number: {{CONDA_BUILD_NUMBER}}
  script: PETSC_DIR=$PREFIX MACOSX_DEPLOYMENT_TARGET=10.9 pip install --no-deps .
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - python
    - pip
    - numpy
    - {{mpi}}
    - petsc {{version[:3]}}*
  run:
    - python
    - numpy
    - {{mpi}}
    - petsc {{version[:3]}}*

test:
  imports:
    - petsc4py
    - petsc4py.PETSc

about:
  home: https://bitbucket.org/petsc/petsc4py
  summary: Python bindings for PETSc
  license: BSD 2-Clause
  license_file: LICENSE.rst
