{% set build = 1 %}
{% set version = '3.7.0' %}
{% set md5 = '816a20040a6a477bd637f397c9fb5b6d' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}

package:
  name: petsc4py
  version: {{version}}

source:
  fn: petsc4py-{{version}}.tar.gz
  url: https://bitbucket.org/petsc/petsc4py/downloads/petsc4py-{{version}}.tar.gz
  md5: {{md5}}

build:
  number: {{build}}
  script: PETSC_DIR=$PREFIX pip install --no-deps .
  skip: true  # [win]

requirements:
  build:
    - python
    - pip
    - numpy
    - {{mpi}}
    - petsc {{version[:3]}}*
  run:
    - python
    - numpy
    - {{mpi}}
    - petsc {{version[:3]}}*

test:
  imports:
    - petsc4py
    - petsc4py.PETSc

about:
  home: https://bitbucket.org/petsc/petsc4py
  summary: Python bindings for PETSc
  license: BSD 2-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
