{% set version = "4.5.0" %}

package:
  name: libnetcdf-parallel
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-c/archive/v{{ version }}.tar.gz
  sha256: f7d1cb2a82100b9bf9a1130a50bc5c7baf0de5b5022860ac3e09a0a32f83cf4a
  patches:
    # https://github.com/Unidata/netcdf-c/pull/512
    - back_port_512.patch
    # https://github.com/Unidata/netcdf-c/pull/573
    - back_port_573.patch
    - CMakeLists.patch  # [win]

build:
  number: 3

requirements:
  build:
    - cmake
    - make
    - pkg-config
    - {{ compiler('c') }}
  host:
    - curl
    - zlib
    - {{ mpi }}
    - hdf5 1.10.4 mpi_{{ mpi }}_*
  run:
    - curl
    - zlib
    - {{ mpi }}
    - hdf5 1.10.4 mpi_{{ mpi }}_*

test:
  commands:
    - nc-config --all  # [not win]
    - test -f ${PREFIX}/lib/libnetcdf.a  # [not win]
    - test -f ${PREFIX}/lib/libnetcdf.so  # [linux]
    - test -f ${PREFIX}/lib/libnetcdf.dylib  # [osx]
    - ncdump -h "http://geoport-dev.whoi.edu/thredds/dodsC/estofs/atlantic"
    - ncdump -h "https://data.nodc.noaa.gov/thredds/dodsC/ioos/sccoos/scripps_pier/scripps_pier-2016.nc"
    - ncdump -h "http://oos.soest.hawaii.edu/thredds/dodsC/hioos/model/atm/ncep_pac/NCEP_Pacific_Atmospheric_Model_best.ncd"
    - ncdump -h "http://oos.soest.hawaii.edu/thredds/dodsC/usgs_dem_10m_tinian"
    - ncdump -h "https://www.ncei.noaa.gov/thredds/dodsC/namanl/201609/20160929/namanl_218_20160929_1800_006.grb"
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
  license_file: COPYRIGHT
  summary: 'Libraries and data formats that support array-oriented scientific data.'

