{% set version = "2016.1.0" %}
package:
  name: mshr
  version: {{version}}
source:
  url: https://bitbucket.org/fenics-project/mshr/downloads/mshr-{{version}}.tar.gz
  sha1: 3a6d45bf72b8c18ab4dda9e3570bc6ea66956c3b
  patches:
    - python3.patch  # [py3k]
build:
  number: 0
requirements:
  build:
    - python
    - cmake
    - fenics {{version}}
    - gmp
    - mpfr
  run:
    - python
    - cmake
    - fenics {{version}}
    - gmp
    - mpfr
test:
  imports:
    - mshr
about:
  home: http://fenicsproject.org/
  license: The GNU Lesser General Public License, version 3.0
  summary: 'Mesh generation component of FEniCS'

