{% set petsc_version = '3.7.*' %}

package:
  name: fenics
  version: {{FENICS_VERSION}}

source:
  #git_url: https://bitbucket.org/fenics-project/dolfin.git
  #git_tag: master
  path: /Users/mikaelmortensen/MySoftware/dolfin

build:
  number: {{CONDA_BUILD_NUMBER}}
  skip: true  # [win]
  script_env:
    - FENICS_GIT_TAG
    - FENICS_VERSION

requirements:
  build:
    - python
    - pip
    - gcc  # [linux]
    - boost 1.64.*
    - cmake
    - eigen
    - pkg-config
    - ptscotch
    - toolchain
    - zlib 1.2.*
    - mpich
    - petsc {{petsc_version}}
    - petsc4py {{petsc_version}}
    - slepc {{petsc_version}}
    - slepc4py {{petsc_version}}
    - swig 3.0.12
    - numpy
    - ply
    - six
    - sympy
    - hdf5-parallel
    - subprocess32  # [py2k]
    #- vtk 6.3.0

  run:
    - python
    - setuptools
    - boost 1.64.*
    - cmake
    - eigen
    - gcc  # [linux]
    - mpich
    - petsc {{petsc_version}}
    - petsc4py {{petsc_version}}
    - slepc {{petsc_version}}
    - slepc4py {{petsc_version}}
    - pkg-config
    - ptscotch
    - zlib 1.2.*
    - ply
    - swig 3.0.12
    - numpy
    - six
    - sympy
    - hdf5-parallel
    - subprocess32  # [py2k]
    #- vtk 6.3.0

test:

  source_files:
    - test

  requires:
    - nose
    - pytest
    - git
    - decorator

  imports:
    - dijitso
    - instant
    - ufl
    - ufl.utils
    - ufl.finiteelement
    - ufl.core
    - ufl.corealg
    - ufl.algorithms
    - FIAT
    - ffc
    - ffc.backends
    - ffc.backends.dolfin
    - ffc.backends.ufc
    - ffc.errorcontrol
    - ffc.quadrature
    - dolfin

  commands:
    - instant-clean
    - instant-showcache

    - ufl-version
    - ufl2py --help

    - ffc --help

about:
  home: http://www.fenicsproject.org
  license: LGPL 3.0
  license_file: COPYING.LESSER
  summary: 'FEniCS is a collection of free software for automated, efficient solution of differential equations'

  description: |
    FEniCS is a collection of free software for automated, efficient solution of differential equations
    (<http://fenicsproject.org>). It provides C++ and Python interfaces, and creates effecient solvers via
    expression of finite variational statements in a domain-specific language that are transformed and
    just-in-time compiled into efficient implementations.
  doc_url: http://fenics.readthedocs.io/
  dev_url: https://bitbucket.org/fenics-project/

