package:
  name: ufl
  version: {{FENICS_VERSION}}

source:
  git_url: https://bitbucket.org/fenics-project/ufl
  git_tag: {{GIT_TAG_UFL}}

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  build:
    - python
    - six
    - numpy

  run:
    - python
    - six
    - numpy

test:
  imports:
    - ufl
    - ufl.utils
    - ufl.finiteelement
    - ufl.core
    - ufl.corealg
    - ufl.algorithms

  commands:
#    - ufl-convert --help  # See #55
    - ufl-version
    #- ufl2py --help
#    - form2ufl --help  # See #56

  requires:
    - pytest


about:
  home: http://www.fenicsproject.org
  license: The GNU Lesser General Public License, version 3.0
  summary: 'Unified Form Language'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
