package:
  name: fenicstools
  version: "2017.2.dev"
  
source:
  #fn: 1.6.tar.gz
  #url: https://github.com/mikaem/fenicstools/archive/1.6.tar.gz
  #md5: 27553a9d2c4ffa082583587659f1277a  
  git_url: https://github.com/mikaem/fenicstools.git
  git_tag: master

build:
  number: 4

requirements:
  build:
    - python
    - fenics 2017.2.dev
    - pyvtk
    - h5py-parallel

  run:
    - python
    - fenics 2017.2.dev
    - pyvtk
    - mpi4py
    - h5py-parallel

test:
    requires:
      - fenics 2017.2.dev
      - pyvtk
      - h5py-parallel
      - pytest
    
    imports:
      - dolfin
      - fenicstools

      
# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
