package:
  name: mshr
  #version: "1.6.0"
  version: "1.7.0"

source:
  #fn: mshr-1.6.0.tar.gz
  #url: https://bitbucket.org/fenics-project/mshr/downloads/mshr-1.6.0.tar.gz
  #md5: 44160cccb8a006be27c8d9c33af6a397
  git_url: https://bitbucket.org/fenics-project/mshr
  git_tag: master 

build:
  number: 2
  features:
    - vtk

requirements:
  build:
    - python
    - dolfin ==1.7.0
    - vtk ==5.10.1
    - hdf5 ==1.8.14
    - boost ==1.57.0
    - gmp
    - mpfr

  run:
    - python
    - dolfin ==1.7.0
    - vtk ==5.10.1
    - hdf5 ==1.8.14
    - boost ==1.57.0
    - gmp
    - mpfr

test:
  imports:
    - mshr

about:
  home: http://fenicsproject.org/
  license: The GNU Lesser General Public License, version 3.0
  summary: 'Mesh generation component of FEniCS'

