{% set version = '3.8.0' %}
{% set sha256 = '35a71a5f83d8fbbede20e235613ac51164cc31db7599c5e78938337ac8b35c5f' %}
{% set mpi = os.environ.get('MPI') or 'mpich' %}

package:
  name: slepc4py
  version: {{version}}

source:
  fn: slepc4py-{{version}}.tar.gz
  url: https://bitbucket.org/slepc/slepc4py/downloads/slepc4py-{{version}}.tar.gz
  sha256: {{sha256}}

build:
  number: {{CONDA_BUILD_NUMBER}}
  script: PETSC_DIR=$PREFIX SLEPC_DIR=$PREFIX MACOSX_DEPLOYMENT_TARGET=10.9 pip install --no-deps .
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - python
    - pip
    - numpy
    - {{mpi}}
    - petsc {{version[:3]}}*
    - slepc {{version[:3]}}*
    - petsc4py {{version[:3]}}*
  run:
    - python
    - numpy
    - {{mpi}}
    - petsc {{version[:3]}}*
    - slepc {{version[:3]}}*
    - petsc4py {{version[:3]}}*

test:
  imports:
    - slepc4py
    - slepc4py.SLEPc

about:
  home: https://bitbucket.org/slepc/slepc4py
  summary: Python bindings for SLEPc
  license: BSD 2-Clause
