package:
  name: eigen3
  version: "3.2.1"

source:
  fn: eigen3-3.2.1.tar.gz
  url: http://bitbucket.org/eigen/eigen/get/3.2.1.tar.gz
  sha1: 96709ff139c80861e7b2cf65a9dfca8a8cc46eeb

build:
  number: {{CONDA_BUILD_NUMBER}}
  
requirements:
  build:
    - gcc ==4.8.5
    - cmake

  run:
    - libgcc ==4.8.5

test:
  requires:
    - gcc

  files:
    - test.cc

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
  summary: 'C++ template library for linear algebra'
