package:
  name: fenics
  version: {{FENICS_VERSION}}

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  run:
    - dolfin =={{FENICS_VERSION}}

about:
  home: http://www.fenicsproject.org
  summary: 'FEniCS is a collection of free software for automated, efficient solution of differential equations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
