
package:
  name: mshr
  version: {{FENICS_VERSION}}

source:
  git_url: https://bitbucket.org/fenics-project/mshr
  git_tag: master

build:
  number: 0

requirements:
  build:
    - python
    - cmake
    - fenics {{FENICS_VERSION}}
    - gmp
    - mpfr
  run:
    - python
    - cmake
    - fenics {{FENICS_VERSION}}
    - gmp
    - mpfr
test:
  imports:
    - mshr
about:
  home: http://fenicsproject.org/
  license: The GNU Lesser General Public License, version 3.0
  summary: 'Mesh generation component of FEniCS'

