{% set version = "4.6.2" %}

package:
  name: libnetcdf-parallel
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-c/archive/v{{ version }}.tar.gz
  sha256: 673936c76ae0c496f6dde7e077f5be480afc1e300adb2c200bf56fbe22e5a82a
  patches:
    # https://github.com/Unidata/netcdf-c/pull/512
    #- back_port_512.patch
    # https://github.com/Unidata/netcdf-c/pull/573
    #- back_port_573.patch
    #- CMakeLists.patch  # [win]

build:
  number: 4

requirements:
  host:
    - {{ mpi }}
    - hdf5 1.10.4 mpi_{{ mpi }}_*
    - bzip2
    - curl
    - jpeg
    - zlib
  build:
    - cmake
    - make
    - pkg-config
    - {{ compiler('c') }}
  run:
    - bzip2
    - curl
    - jpeg
    - zlib
    - {{ mpi }}
    - hdf5

test:
  commands:
    - test -f ${PREFIX}/lib/libnetcdf.a  # [not win]
    - test -f ${PREFIX}/lib/libnetcdf${SHLIB_EXT}  # [not win]
    - nc-config --all  # [not win]
#test:
#  commands:
#    - nc-config --all  # [not win]
#    - test -f ${PREFIX}/lib/libnetcdf.a  # [not win]
#    - test -f ${PREFIX}/lib/libnetcdf.so  # [linux]
#    - test -f ${PREFIX}/lib/libnetcdf.dylib  # [osx]
#    - ncdump -h "http://geoport-dev.whoi.edu/thredds/dodsC/estofs/atlantic"
#    - ncdump -h "https://data.nodc.noaa.gov/thredds/dodsC/ioos/sccoos/scripps_pier/scripps_pier-2016.nc"
#    - ncdump -h "http://oos.soest.hawaii.edu/thredds/dodsC/hioos/model/atm/ncep_pac/NCEP_Pacific_Atmospheric_Model_best.ncd"
#    - ncdump -h "http://oos.soest.hawaii.edu/thredds/dodsC/usgs_dem_10m_tinian"
#    - ncdump -h "https://www.ncei.noaa.gov/thredds/dodsC/namanl/201609/20160929/namanl_218_20160929_1800_006.grb"
#    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
#    #- conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
  summary: 'Libraries and data formats that support array-oriented scientific data.'
