package:
  name: petsc
  version: "3.7.3"

source:
  fn: petsc-lite-3.7.3.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.7.3.tar.gz
  md5: 74a81a79347ada5f0ecf92ff5d0637f4

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  build:
    - python
    - openblas
    - mpi4py
    - gcc-5 ==5.3.0
    - cmake

  run:
    - python
    - openblas
    - mpi4py

test:
  requires:
    - gcc

about:
  home: http://www.mcs.anl.gov/petsc/
  license: PETSc
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
