{% set blas = os.environ.get('BLAS') or 'openblas' %}
{% set openblas_version = '0.2.19' %}

package:
  name: petsc
  version: "3.7.3"

source:
  fn: petsc-lite-3.7.3.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.7.3.tar.gz
  md5: 74a81a79347ada5f0ecf92ff5d0637f4

build:
  number: {{CONDA_BUILD_NUMBER}}
  binary_relocation: true
  detect_binary_files_with_prefix: true
  skip: true  # [win]
  features:
    - blas_{{blas}}

requirements:
  build:
    - python
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas {{openblas_version}}
    {% endif %}
    - mpi4py
    - hdf5-parallel
    - gcc
    - cmake

  run:
    - python
    - mpi4py
    - blas 1.* {{blas}}
    {% if blas == 'openblas' %}
    - openblas {{openblas_version}}
    {% endif %}

test:
  source_files:
    - src/snes/examples/tests

  requires:
    - gcc

about:
  home: http://www.mcs.anl.gov/petsc/
  license: PETSc
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
