package:
  name: slepc
  version: "3.7.2"

source:
  git_rev: 86150f397039
  git_url: https://bitbucket.org/slepc/slepc.git

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  build:
    - python
    - gcc
    - petsc <=3.7.3

  run:
    - python
    - petsc <=3.7.3

test:
  requires:
    - gcc
    - pkg-config

  commands:
    - PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig pkg-config --cflags SLEPc

about:
  home: http://www.grycap.upv.es/slepc/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
