package:
  name: instant
  version: {{FENICS_VERSION}}

source:
  git_url: https://bitbucket.org/fenics-project/instant
  git_tag: {{GIT_TAG_INSTANT}}

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  build:
    - python
    - numpy
    - swig

  run:
    - python
    - numpy
    - cmake
    - swig
    - gcc ==4.8.5
    - libgcc ==4.8.5

test:
  imports:
    - instant

  commands:
    - instant-clean
    - instant-showcache

  requires:
    - pytest

about:
  home: http://www.fenicsproject.org
  license: BSD License or The GNU Lesser General Public License, version 3.0
  summary: 'Instant Inlining of C/C++ in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
