package:
  name: slepc
  version: "3.7.2"

source:
  git_rev: 86150f397039
  git_url: https://bitbucket.org/slepc/slepc.git

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  build:
    - python
    - petsc <=3.7.3

  run:
    - python
    - petsc <=3.7.3

about:
  home: http://www.grycap.upv.es/slepc/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'
