{% set version = "1.4.2" %}

package:
  name: netcdf4-parallel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/netCDF4/netCDF4-{{version}}.tar.gz
  sha256: b934af350459cf9041bcdf5472e2aa56ed7321c018d918e9f325ec9a1f9d1a30

build:
  number: 7
  entry_points:
    - ncinfo = netCDF4.utils:ncinfo
    - nc4tonc3 = netCDF4.utils:nc4tonc3
    - nc3tonc4 = netCDF4.utils:nc3tonc4

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python {{ python }}
    - pip
    - numpy
    - cython
    - cftime >=1.0.1
    - {{ mpi }}
    - hdf5 * mpi_{{ mpi }}_*
    - libnetcdf-parallel 4.6.*
  run:
    - python
    - setuptools
    - numpy
    - mpi4py
    - cftime
    - {{ mpi }}
    - hdf5 * mpi_{{ mpi }}_*
    - libnetcdf-parallel

test:
  imports:
    - netCDF4
    - cftime
  commands:
    - ncinfo -h
    - nc4tonc3 -h
    - nc3tonc4 -h

about:
  home: http://github.com/Unidata/netcdf4-python
  license: OSI Approved and MIT
  summary: 'Provides an object-oriented python interface to the netCDF version 4 library.'
  dev_url: https://github.com/Unidata/netcdf4-python
  doc_url: https://unidata.github.io/netcdf4-python
