package:
  name: dolfin
  version: {{FENICS_VERSION}}

source:
  #git_url: https://bitbucket.org/fenics-project/dolfin
  #git_tag: {{GIT_TAG_DOLFIN}}
  path: /Users/mikaelmortensen/MySoftware/dolfin

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  build:
    - python
    - cmake
    - libxml2
    - boost ==1.61
    - mpi4py
    - eigen
    - petsc <=3.7.3
    - petsc4py <=3.7.0
    - slepc <=3.7.2
    - vtk ==6.3.0
    - hdf5-parallel
    - sphinx
    - swig 
    - numpy
    - ffc =={{FENICS_VERSION}}
    - ply ==3.8

  run:
    - python
    - boost ==1.61
    - mpi4py
    - eigen
    - petsc <=3.7.3
    - petsc4py <=3.7.0
    - slepc <=3.7.2
    - vtk ==6.3.0
    - hdf5-parallel
    - swig
    - numpy
    - ffc =={{FENICS_VERSION}}
    - ufl =={{FENICS_VERSION}}
    - ply ==3.8

test:
  imports:
    - dolfin

about:
  home: http://www.fenicsproject.org
  license: The GNU Lesser General Public License, version 3.0
  summary: 'C++/Python library for solving differential equations'


